# fly.toml app configuration file generated for shy-night-2038 on 2023-08-07T13:11:38-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shy-night-2038"
primary_region = "lax"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
